version: '3.7'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=SecurePa55w0rd
    volumes:
        - ./sql:/scripts
        - ../_common/wait-for-it.sh:/scripts/wait-for-it.sh
    entrypoint: [ "/bin/bash", "-c", "/scripts/db-start.sh" ]
    networks:
      openfire-net:
        ipv4_address: 172.60.0.11
  
  xmpp1:
    image: "openfire:${OPENFIRE_TAG}"
    ports:
      - "5222:5222"
      - "5269:5269"
      - "7070:7070"
      - "7443:7443"
      - "9090:9090"
    depends_on:
      - "db"
    volumes:
      - ./_data/xmpp/conf:/var/lib/openfire/conf
      - ./_data/plugins:/opt/plugins
      - ../_common/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "-s", "db:1433", "--", "/sbin/entrypoint.sh"]
    networks:
      openfire-net:
        ipv4_address: 172.60.0.10
    extra_hosts:
      - "xmpp.localhost.example:172.60.0.10"
      - "conference.xmpp.localhost.example:172.60.0.10"

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

networks:
  openfire-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.60.0.0/24
